sudo: required
language: crystal
crystal:
  - latest

services:
  - docker

stages:
  - test
  - build
  - publish

jobs:
  include:
    - stage: test
      name: "Compile and run unit tests"
      install:
        - make shards
      script:
        - make
        - make test

    - stage: build
      name: "Build the Docker image"
      install:
        - true # Just a hack to skip the install phase
      script:
        - docker build -t coin .
        - docker run coin -v
      if: branch = master OR tag IS present

    - stage: publish
      name: "Publish the Docker image to DockerHub"
      before_script:
        - echo "$DH_PASS" | docker login -u caian --password-stdin
      install:
        - true
      script:
        - docker build -t $DH_REPO:$TRAVIS_TAG .
        - docker push $DH_REPO:$TRAVIS_TAG
        - docker tag $DH_REPO:$TRAVIS_TAG $DH_REPO:latest
        - docker push $DH_REPO:latest
      env:
        - DH_REPO="caian/coin"
      if: tag IS present
